version: '3'
services:
  client:
    image: aiwanderer/multi-client
    environment:
      - WDS_SOCKET_PORT=0
    volumes: 
      - /home/node/app/node_modules
      - ${WEBAPP_STORAGE_HOME}/client:/home/node/app
  api:
    depends_on:
      - postgres
    image: aiwanderer/multi-server
    volumes: 
      - /home/node/app/node_modules
      - ${WEBAPP_STORAGE_HOME}/server:/home/node/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  nginx:
    restart: always
    depends_on:
      - api
      - client
    image: aiwanderer/multi-nginx
    ports:
      - '80:80'
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: "redis:latest"
  worker:
    image: aiwanderer/multi-worker
    volumes: 
      - /home/node/app/node_modules
      - ${WEBAPP_STORAGE_HOME}/worker:/home/node/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

