name: Build/Push Images to DockerHub and Deploy Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch: 

env:
  AZURE_WEBAPP_NAME: 'docker-react-complex'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: check working directory
        run: pwd
      
      - name: Build and Push Client
        uses: docker/build-push-action@v5
        with:
          context: complex/client/
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/multi-client:latest
      
      - name: Build and Push Nginx
        uses: docker/build-push-action@v5
        with:
          context: ./nginx
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/multi-nginx:latest

      - name: Build and Push Server
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/multi-server:latest

      - name: Build and Push Worker
        uses: docker/build-push-action@v5
        with:
          context: ./worker
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/multi-worker:latest
      
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: false
          environment: azurecloud
          allow-no-subscriptions: false
          audience: api://AzureADTokenExchange
          auth-type: SERVICE_PRINCIPAL
          # Command to create service principal in az cli
          # az ad sp create-for-rbac --name udemy-app1-sp --role Contributor --scopes /subscriptions/3ec02c9b-5e63-46a0-ba5e-f0c2ed5505fb --sdk-auth | jq '{clientId: .clientId, clientSecret: .clientSecret, tenantId: .tenantId, subscriptionId: .subscriptionId}'

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
